#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
workspace_root="$(cd "${script_dir}/.." && pwd)"
host_name="$(hostname | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9._-' | sed 's/[.]/-/g')"
host_name="${host_name:-mac}"

memory_out="${workspace_root}/memory/mac-codex-memory.md"
skills_out="${workspace_root}/skills/mac-codex/${host_name}"
generated_at="$(date '+%Y-%m-%d %H:%M:%S %z')"

mkdir -p "${workspace_root}/memory" "$(dirname "${skills_out}")"

{
  printf '# Mac Codex Memory Export\n\n'
  printf 'Generated by scripts/collect-mac-codex-state.sh.\n'
  printf 'Generated at: %s\n' "${generated_at}"
  printf 'Host: %s\n\n' "${host_name}"
  printf 'This is committed to the private GitHub repo for cross-device Codex context.\n'
  printf 'Do not add auth files, API keys, tokens, .env contents, or company secrets here.\n\n'

  printf '## ~/.codex/memories\n\n'
  if [ -d "${HOME}/.codex/memories" ]; then
    find "${HOME}/.codex/memories" -maxdepth 1 -type f | sort | while IFS= read -r file; do
      name="$(basename "${file}")"
      printf '### %s\n\n' "${name}"
      sed -n '1,240p' "${file}" || true
      printf '\n\n'
    done
  else
    printf 'No ~/.codex/memories directory found.\n\n'
  fi

  printf '## ~/.codex/config.toml Metadata\n\n'
  if [ -f "${HOME}/.codex/config.toml" ]; then
    sed -E 's/(api_key|token|secret|password)[[:space:]]*=.*/\1 = "<redacted>"/I' "${HOME}/.codex/config.toml" | sed -n '1,180p'
    printf '\n'
  else
    printf 'No ~/.codex/config.toml found.\n'
  fi
} > "${memory_out}.tmp"
mv "${memory_out}.tmp" "${memory_out}"
printf 'Wrote %s\n' "${memory_out}"

rm -rf "${skills_out}"
mkdir -p "${skills_out}"

if [ -d "${HOME}/.codex/skills" ]; then
  find "${HOME}/.codex/skills" -mindepth 1 -maxdepth 1 | sort | while IFS= read -r skill_dir; do
    [ -d "${skill_dir}" ] || continue
    skill_name="$(basename "${skill_dir}")"
    case "${skill_name}" in
      .system|.cache|cache|tmp|node_modules|.git)
        continue
        ;;
    esac
    if [ -f "${skill_dir}/SKILL.md" ] || [ -f "${skill_dir}/DESCRIPTION.md" ]; then
      mkdir -p "${skills_out}/${skill_name}"
      rsync -aL \
        --exclude '.git' \
        --exclude 'node_modules' \
        --exclude '__pycache__' \
        --exclude '.DS_Store' \
        --exclude '*.log' \
        --exclude '*.tmp' \
        "${skill_dir}/" "${skills_out}/${skill_name}/"
      printf 'Collected Mac Codex skill: %s\n' "${skill_name}"
    fi
  done
fi

if grep -RInE 'sk-[A-Za-z0-9_-]{20,}|OPENAI_API_KEY|ANTHROPIC_API_KEY|TELEGRAM_BOT_TOKEN|BEGIN .*PRIVATE KEY|password[[:space:]]*=|token[[:space:]]*=' \
  "${memory_out}" "${skills_out}" >/tmp/mac-codex-secret-scan.txt 2>/dev/null; then
  printf '\nPotential secret-like content found. Review before pushing:\n' >&2
  cat /tmp/mac-codex-secret-scan.txt >&2
  exit 2
fi

printf 'Mac Codex state collection complete.\n'
