#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
workspace_root="$(cd "${script_dir}/.." && pwd)"
host_name="$(hostname | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9._-' | sed 's/[.]/-/g')"
host_name="${host_name:-mac}"

memory_out="${workspace_root}/memory/mac-codex-memory.md"
agent_skills_out="${workspace_root}/skills/mac-agent/${host_name}"
generated_at="$(date '+%Y-%m-%d %H:%M:%S %z')"

mkdir -p "${workspace_root}/memory" "$(dirname "${agent_skills_out}")"

expand_path() {
  local raw="$1"
  case "${raw}" in
    "~") printf '%s\n' "${HOME}" ;;
    "~/"*) printf '%s/%s\n' "${HOME}" "${raw#~/}" ;;
    "\$HOME") printf '%s\n' "${HOME}" ;;
    "\$HOME/"*) printf '%s/%s\n' "${HOME}" "${raw#\$HOME/}" ;;
    *) printf '%s\n' "${raw}" ;;
  esac
}

add_configured_roots() {
  local config_file="$1"
  [ -f "${config_file}" ] || return 0

  while IFS= read -r line || [ -n "${line}" ]; do
    line="${line%%#*}"
    line="$(printf '%s' "${line}" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    [ -n "${line}" ] || continue
    skill_roots+=("$(expand_path "${line}")")
  done < "${config_file}"
}

write_mac_memory_export() {
  {
    printf '# Mac Codex Memory Export\n\n'
    printf 'Generated by scripts/collect-mac-agent-state.sh.\n'
    printf 'Generated at: %s\n' "${generated_at}"
    printf 'Host: %s\n\n' "${host_name}"
    printf 'This is committed to the private GitHub repo for cross-device context.\n'
    printf 'Do not add auth files, API keys, tokens, .env contents, or company secrets here.\n\n'

    printf '## ~/.codex/memories\n\n'
    if [ -d "${HOME}/.codex/memories" ]; then
      find "${HOME}/.codex/memories" -maxdepth 1 -type f | sort | while IFS= read -r file; do
        name="$(basename "${file}")"
        printf '### %s\n\n' "${name}"
        sed -n '1,240p' "${file}" || true
        printf '\n\n'
      done
    else
      printf 'No ~/.codex/memories directory found.\n\n'
    fi

    printf '## ~/.codex/config.toml Metadata\n\n'
    if [ -f "${HOME}/.codex/config.toml" ]; then
      sed -E 's/(api_key|token|secret|password)[[:space:]]*=.*/\1 = "<redacted>"/I' "${HOME}/.codex/config.toml" | sed -n '1,180p'
      printf '\n'
    else
      printf 'No ~/.codex/config.toml found.\n'
    fi
  } > "${memory_out}.tmp"
  mv "${memory_out}.tmp" "${memory_out}"
  printf 'Wrote %s\n' "${memory_out}"
}

copy_one_skill() {
  local skill_dir="$1"
  local root="$2"
  local skill_name
  local rel_root
  local safe_root
  local dest_dir

  skill_name="$(basename "${skill_dir}")"
  case "${skill_name}" in
    .system|.cache|cache|tmp|node_modules|.git|__pycache__)
      return 0
      ;;
  esac

  [ -f "${skill_dir}/SKILL.md" ] || [ -f "${skill_dir}/DESCRIPTION.md" ] || return 0

  rel_root="${root/#${HOME}/~}"
  safe_root="$(printf '%s' "${rel_root}" | sed 's/^~/HOME/; s/[^A-Za-z0-9._-]/__/g')"
  dest_dir="${agent_skills_out}/${safe_root}/${skill_name}"
  mkdir -p "${dest_dir}"

  if command -v rsync >/dev/null 2>&1; then
    rsync -aL \
      --exclude '.git' \
      --exclude 'node_modules' \
      --exclude '__pycache__' \
      --exclude '.DS_Store' \
      --exclude '*.log' \
      --exclude '*.tmp' \
      --exclude '.env' \
      --exclude '.env.*' \
      --exclude 'auth.json' \
      --exclude '*.key' \
      --exclude '*.pem' \
      "${skill_dir}/" "${dest_dir}/"
  else
    cp -R "${skill_dir}/." "${dest_dir}/"
    rm -rf "${dest_dir}/.git" "${dest_dir}/node_modules" "${dest_dir}/__pycache__"
    find "${dest_dir}" \( -name '.DS_Store' -o -name '*.log' -o -name '*.tmp' -o -name '.env' -o -name '.env.*' -o -name 'auth.json' -o -name '*.key' -o -name '*.pem' \) -delete
  fi

  printf '%s\n' "- \`${rel_root}/${skill_name}\` -> \`${safe_root}/${skill_name}\`" >> "${agent_skills_out}/MANIFEST.md"
  printf 'Collected original AGENT skill: %s/%s\n' "${rel_root}" "${skill_name}"
}

collect_agent_skills() {
  skill_roots=()
  add_configured_roots "${workspace_root}/config/agent-skill-roots.txt"
  add_configured_roots "${workspace_root}/config/agent-skill-roots.${host_name}.txt"

  if [ "${#skill_roots[@]}" -eq 0 ]; then
    skill_roots=(
      "${HOME}/.agents/skills"
      "${HOME}/AGENT/.agents/skills"
      "${HOME}/Agent/.agents/skills"
      "${HOME}/agent/.agents/skills"
      "${HOME}/AGENT/skills"
      "${HOME}/Agent/skills"
      "${HOME}/agent/skills"
      "${HOME}/.hermes/skills"
    )
  fi

  rm -rf "${agent_skills_out}"
  mkdir -p "${agent_skills_out}"

  {
    printf '# Mac Original AGENT Skills\n\n'
    printf 'Host: `%s`\n\n' "${host_name}"
    printf 'Generated at: `%s`\n\n' "${generated_at}"
    printf 'These are copied from the original AGENT skill folders on the Mac.\n'
    printf 'They are not rewritten as Codex-only skills.\n\n'
    printf '## Scanned Roots\n\n'
    for root in "${skill_roots[@]}"; do
      if [ -d "${root}" ]; then
        printf '%s\n' "- \`${root/#${HOME}/~}\`"
      else
        printf '%s\n' "- \`${root/#${HOME}/~}\` (missing, skipped)"
      fi
    done
    printf '\n## Copied Skills\n\n'
  } > "${agent_skills_out}/MANIFEST.md"

  for root in "${skill_roots[@]}"; do
    [ -d "${root}" ] || continue
    find "${root}" -mindepth 1 -maxdepth 1 -type d | sort | while IFS= read -r skill_dir; do
      copy_one_skill "${skill_dir}" "${root}"
    done
  done

  if ! grep -q -- ' -> ' "${agent_skills_out}/MANIFEST.md"; then
    printf '_No original AGENT skills found._\n' >> "${agent_skills_out}/MANIFEST.md"
  fi
}

write_mac_memory_export
collect_agent_skills

secret_pattern='sk-or-v1-[A-Za-z0-9_-]{40,}|sk-ant-[A-Za-z0-9_-]{40,}|OPENAI_API_KEY[[:space:]]*=[[:space:]]*["'\'']?sk-[A-Za-z0-9_-]{20,}|ANTHROPIC_API_KEY[[:space:]]*=[[:space:]]*["'\'']?sk-[A-Za-z0-9_-]{20,}|TELEGRAM_BOT_TOKEN[[:space:]]*=[[:space:]]*["'\'']?[0-9]{8,}:[A-Za-z0-9_-]{20,}|BEGIN (RSA |OPENSSH |EC |DSA )?PRIVATE KEY'

if grep -RInE "${secret_pattern}" \
  "${memory_out}" "${agent_skills_out}" >/tmp/mac-agent-secret-scan.txt 2>/dev/null; then
  printf '\nPotential secret-like content found. Review before pushing:\n' >&2
  cat /tmp/mac-agent-secret-scan.txt >&2
  rm -f /tmp/mac-agent-secret-scan.txt
  exit 2
fi
rm -f /tmp/mac-agent-secret-scan.txt

printf 'Mac AGENT memory/skill collection complete.\n'
