#!/usr/bin/env bash
set -euo pipefail

generated_at="${1:-unknown}"
out="/mnt/f/AGENT/memory/hermes-raw-memory-export.md"
tmp="${out}.tmp"

{
  printf '# Hermes Raw Memory Export\n\n'
  printf 'Generated by scripts/sync-agent-memory.ps1 -ExportHermesRaw.\n'
  printf 'Generated at: %s\n\n' "$generated_at"
  printf 'This file may contain sensitive personal context. Do not paste it into public chats,\n'
  printf 'issues, logs, or external tools.\n\n'
  printf '## USER.md\n\n'
  test -f /root/.hermes/memories/USER.md && sed -n '1,240p' /root/.hermes/memories/USER.md || true
  printf '\n\n## MEMORY.md\n\n'
  test -f /root/.hermes/memories/MEMORY.md && sed -n '1,240p' /root/.hermes/memories/MEMORY.md || true
  printf '\n'
} > "$tmp"

mv "$tmp" "$out"
