#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
workspace_root="$(cd "${script_dir}/.." && pwd)"
memory_dir="${workspace_root}/memory"
out="${memory_dir}/mac-codex-raw-memory-export.md"
tmp="${out}.tmp"
generated_at="$(date '+%Y-%m-%d %H:%M:%S %z')"

mkdir -p "${memory_dir}"

{
  printf '# Mac Codex Raw Memory Export\n\n'
  printf 'Generated by scripts/export-mac-codex-memory.sh.\n'
  printf 'Generated at: %s\n\n' "${generated_at}"
  printf 'This file may contain private local context. Do not commit, paste, or upload it publicly.\n\n'

  printf '## Shared Memory Link\n\n'
  if [ -f "${memory_dir}/SHARED_AGENT_MEMORY.md" ]; then
    printf 'Shared memory file exists at: %s\n\n' "${memory_dir}/SHARED_AGENT_MEMORY.md"
  else
    printf 'Shared memory file is missing at: %s\n\n' "${memory_dir}/SHARED_AGENT_MEMORY.md"
  fi

  printf '## ~/.codex/memories\n\n'
  if [ -d "${HOME}/.codex/memories" ]; then
    find "${HOME}/.codex/memories" -maxdepth 1 -type f | sort | while IFS= read -r file; do
      name="$(basename "${file}")"
      printf '### %s\n\n' "${name}"
      sed -n '1,240p' "${file}" || true
      printf '\n\n'
    done
  else
    printf 'No ~/.codex/memories directory found.\n\n'
  fi

  printf '## ~/.codex/config.toml Metadata\n\n'
  if [ -f "${HOME}/.codex/config.toml" ]; then
    sed -E 's/(api_key|token|secret|password)[[:space:]]*=.*/\1 = "<redacted>"/I' "${HOME}/.codex/config.toml" | sed -n '1,160p'
    printf '\n'
  else
    printf 'No ~/.codex/config.toml found.\n'
  fi
} > "${tmp}"

mv "${tmp}" "${out}"
printf 'Exported Mac Codex memory to %s\n' "${out}"
